services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    healthcheck:
      test: ["CMD", "bash", "-lc", "</dev/tcp/localhost/2181"]
      interval: 5s
      timeout: 3s
      retries: 20

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL1://0.0.0.0:9093,EXTERNAL2://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://localhost:9092,EXTERNAL1://${172.31.15.3:-localhost}:9093,EXTERNAL2://${EXTERNAL_IP_2:-localhost}:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL1:PLAINTEXT,EXTERNAL2:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "bash", "-lc", "</dev/tcp/localhost/9092"]
      interval: 5s
      timeout: 3s
      retries: 30

  # issuance:
  #   build: ./backend/issuance-service
  #   environment:
  #     - KAFKA_BROKER=kafka:9092
  #   depends_on:
  #     kafka:
  #       condition: service_healthy
  #   ports:
  #     - "3001:3001"

  # verification:
  #   build: ./backend/verification-service
  #   environment:
  #     - KAFKA_BROKER=kafka:9092
  #   depends_on:
  #     kafka:
  #       condition: service_healthy
  #   ports:
  #     - "3002:3002"
