
apiVersion: apps/v1
kind: Deployment
metadata:
  name: verification-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: verification
  template:
    metadata:
      labels:
        app: verification
    spec:
      containers:
        - name: verification
          image: verification-service:latest
          env:
            - name: PORT
              value: "3002"
          ports:
            - containerPort: 3002
